version: '3'
services:
  mariadb:
    image: mariadb
    container_name: db_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <your_root_password>
      MYSQL_DATABASE: <your_database_name>
      MYSQL_USER: <your_user_name>
      MYSQL_PASSWORD: <your_user_password>
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql